// Sin dependencias: un diccionario plano. Para cincuenta cadenas una libreria
// de i18n cuesta mas que lo que resuelve.
// Aqui no entra nada de React, para poder comprobar el diccionario con node.

export const LANGS = [
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'en', name: 'English', flag: '🇬🇧' },
  { code: 'fr', name: 'Français', flag: '🇫🇷' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
  { code: 'it', name: 'Italiano', flag: '🇮🇹' },
  { code: 'pt', name: 'Português', flag: '🇵🇹' },
]

const DICT = {
  es: {
    'app.name': 'Munchkin Salas',
    'app.tagline':
      'Contador de niveles y equipo para Munchkin. Cada uno lleva su personaje desde su móvil y la mesa lo ve todo.',
    'setup.empty': 'Todavía no hay nadie en la partida.',
    'setup.add': 'Añadir jugador',
    'setup.start': 'Empezar',
    'setup.player': 'Jugador {n}',
    'setup.remove': 'Quitar a {name}',
    'setup.color': 'Color de {name}',
    'goal.label': 'Se gana al nivel',
    'goal.down': 'Bajar el nivel objetivo',
    'goal.up': 'Subir el nivel objetivo',
    'goal.locked': 'Se decide antes de empezar',
    'sex.male': 'Hombre',
    'sex.female': 'Mujer',
    'stat.level': 'Nivel',
    'stat.gear': 'Equipo',
    'stat.bad': 'Desventajas',
    'stat.badLong': 'Desventajas (resta)',
    'stat.type': 'Escribir {label}',
    'stat.sex': 'Sexo',
    'stat.force': 'Fuerza',
    'stat.down': 'Bajar {label}',
    'stat.up': 'Subir {label}',
    'stat.lv': 'Nv',
    'sheet.back': 'Volver al tablero',
    'player.map': 'Ver el mapa',
    'player.mine': 'Mi ficha',
    'player.switch': 'Cambiar de jugador',
    'board.menu': 'Opciones de la partida',
    'board.who': '¿Quién es este aparato?',
    'board.edit': 'Editar jugadores',
    'board.restart': 'Reiniciar partida',
    'board.sure': '¿Estás seguro?',
    'board.keep': 'Seguir jugando',
    'board.restartOk': 'Reiniciar',
    'role.who': '¿Quién eres?',
    'role.table': 'Mesa',
    'role.tableHint': 'La pantalla del centro, meramente visual, no juega.',
    'role.orPick': 'o coge tu personaje',
    'role.taken': 'ya lo lleva otro',
    'role.orNew': 'o si hoy toca otra cosa',
    'role.newGame': 'Empezar de cero',
    'role.newGameHint': 'Se borra todo y empiezas con la lista vacía.',
    'room.title': 'Sala',
    'room.scan': 'Escanea para entrar',
    'room.orCode': 'O entra a mano con este código:',
    'room.device': '{n} aparato',
    'room.devices': '{n} aparatos',
    'room.privacy':
      'Los nombres viajan a un servidor en Cloudflare y la sala se borra sola a las 24 h.',
    'room.leave': 'Salir de la sala',
    'room.done': 'Listo',
    'room.createHint': 'Crea una sala desde la pantalla de la mesa y que cada uno entre con su móvil.',
    'room.create': 'Crear sala',
    'room.orJoin': 'o entra en una que ya exista',
    'room.code': 'Código',
    'room.enter': 'Entrar',
    'room.notReady':
      'Para jugar con varios aparatos hay que desplegar el servidor de salas. Mientras tanto la app funciona entera en este aparato.',
    'status.idle': 'Sin sala',
    'status.connecting': 'Conectando…',
    'status.online': 'Conectado',
    'status.offline': 'Sin conexión',
    'error.missing': 'Esa sala ya no existe.',
    'error.create': 'No se pudo crear la sala. ¿Hay internet?',
    'error.code': 'El código son cuatro letras.',
    'error.tooMany': 'Demasiadas salas seguidas. Prueba dentro de un minuto.',
    'boundary.title': 'Se ha atascado',
    'boundary.hint':
      'La partida guardada en este aparato no se puede leer. Empezando de cero se arregla.',
    'boundary.action': 'Empezar de cero',
    'lang.label': 'Idioma',
  },

  en: {
    'app.name': 'Munchkin Rooms',
    'app.tagline':
      'Level and gear counter for Munchkin. Everyone runs their own character from their phone while the table screen shows the lot.',
    'setup.empty': 'Nobody in the game yet.',
    'setup.add': 'Add player',
    'setup.start': 'Start',
    'setup.player': 'Player {n}',
    'setup.remove': 'Remove {name}',
    'setup.color': 'Colour for {name}',
    'goal.label': 'Win at level',
    'goal.down': 'Lower the target level',
    'goal.up': 'Raise the target level',
    'goal.locked': 'Set before the game starts',
    'sex.male': 'Male',
    'sex.female': 'Female',
    'stat.level': 'Level',
    'stat.gear': 'Gear',
    'stat.bad': 'Penalties',
    'stat.badLong': 'Penalties (subtract)',
    'stat.type': 'Type {label}',
    'stat.sex': 'Sex',
    'stat.force': 'Power',
    'stat.down': 'Lower {label}',
    'stat.up': 'Raise {label}',
    'stat.lv': 'Lv',
    'sheet.back': 'Back to the board',
    'player.map': 'See the board',
    'player.mine': 'My sheet',
    'player.switch': 'Switch player',
    'board.menu': 'Game options',
    'board.who': 'What is this device?',
    'board.edit': 'Edit players',
    'board.restart': 'Reset game',
    'board.sure': 'Are you sure?',
    'board.keep': 'Keep playing',
    'board.restartOk': 'Reset',
    'role.who': 'Who are you?',
    'role.table': 'Table',
    'role.tableHint': 'The screen in the middle. Just for looking, does not play.',
    'role.orPick': 'or take your character',
    'role.taken': 'someone else has it',
    'role.orNew': 'or if today is a fresh one',
    'role.newGame': 'Start from scratch',
    'role.newGameHint': 'Wipes everything and starts with an empty list.',
    'room.title': 'Room',
    'room.scan': 'Scan to join',
    'room.orCode': 'Or join by hand with this code:',
    'room.device': '{n} device',
    'room.devices': '{n} devices',
    'room.privacy': 'Names travel to a server on Cloudflare and the room deletes itself after 24 h.',
    'room.leave': 'Leave the room',
    'room.done': 'Done',
    'room.createHint': 'Create the room on the table screen and let everyone join from their phone.',
    'room.create': 'Create room',
    'room.orJoin': 'or join one that already exists',
    'room.code': 'Code',
    'room.enter': 'Join',
    'room.notReady':
      'Playing across devices needs the room server deployed. Until then the app works fully on this device.',
    'status.idle': 'No room',
    'status.connecting': 'Connecting…',
    'status.online': 'Connected',
    'status.offline': 'Offline',
    'error.missing': 'That room no longer exists.',
    'error.create': 'Could not create the room. Any internet?',
    'error.code': 'The code is four letters.',
    'error.tooMany': 'Too many rooms in a row. Try again in a minute.',
    'boundary.title': 'It got stuck',
    'boundary.hint': 'The game saved on this device cannot be read. Starting over fixes it.',
    'boundary.action': 'Start over',
    'lang.label': 'Language',
  },

  fr: {
    'app.name': 'Munchkin Salles',
    'app.tagline':
      'Compteur de niveaux et d’équipement pour Munchkin. Chacun gère son personnage depuis son téléphone et l’écran de table montre tout.',
    'setup.empty': 'Personne dans la partie pour le moment.',
    'setup.add': 'Ajouter un joueur',
    'setup.start': 'Commencer',
    'setup.player': 'Joueur {n}',
    'setup.remove': 'Retirer {name}',
    'setup.color': 'Couleur de {name}',
    'goal.label': 'On gagne au niveau',
    'goal.down': 'Baisser le niveau visé',
    'goal.up': 'Augmenter le niveau visé',
    'goal.locked': 'À décider avant de commencer',
    'sex.male': 'Homme',
    'sex.female': 'Femme',
    'stat.level': 'Niveau',
    'stat.gear': 'Équipement',
    'stat.bad': 'Malus',
    'stat.badLong': 'Malus (soustrait)',
    'stat.type': 'Saisir {label}',
    'stat.sex': 'Sexe',
    'stat.force': 'Force',
    'stat.down': 'Baisser {label}',
    'stat.up': 'Augmenter {label}',
    'stat.lv': 'Niv',
    'sheet.back': 'Retour au plateau',
    'player.map': 'Voir le plateau',
    'player.mine': 'Ma fiche',
    'player.switch': 'Changer de joueur',
    'board.menu': 'Options de la partie',
    'board.who': 'Cet appareil, c’est quoi ?',
    'board.edit': 'Modifier les joueurs',
    'board.restart': 'Réinitialiser la partie',
    'board.sure': 'C’est sûr ?',
    'board.keep': 'Continuer à jouer',
    'board.restartOk': 'Réinitialiser',
    'role.who': 'Qui es-tu ?',
    'role.table': 'Table',
    'role.tableHint': 'L’écran du milieu, purement visuel, ne joue pas.',
    'role.orPick': 'ou prends ton personnage',
    'role.taken': 'déjà pris par un autre',
    'role.orNew': 'ou si aujourd’hui on repart',
    'role.newGame': 'Repartir de zéro',
    'role.newGameHint': 'Tout s’effface et tu repars avec la liste vide.',
    'room.title': 'Salle',
    'room.scan': 'Scanne pour entrer',
    'room.orCode': 'Ou entre à la main avec ce code :',
    'room.device': '{n} appareil',
    'room.devices': '{n} appareils',
    'room.privacy':
      'Les noms partent vers un serveur chez Cloudflare et la salle s’efface toute seule au bout de 24 h.',
    'room.leave': 'Quitter la salle',
    'room.done': 'C’est bon',
    'room.createHint': 'Crée la salle sur l’écran de table et que chacun entre depuis son téléphone.',
    'room.create': 'Créer une salle',
    'room.orJoin': 'ou rejoins-en une qui existe déjà',
    'room.code': 'Code',
    'room.enter': 'Entrer',
    'room.notReady':
      'Jouer à plusieurs appareils demande le serveur de salles déployé. En attendant, l’appli marche entièrement ici.',
    'status.idle': 'Pas de salle',
    'status.connecting': 'Connexion…',
    'status.online': 'Connecté',
    'status.offline': 'Hors ligne',
    'error.missing': 'Cette salle n’existe plus.',
    'error.create': 'Impossible de créer la salle. Il y a du réseau ?',
    'error.code': 'Le code fait quatre lettres.',
    'error.tooMany': 'Trop de salles d’affilée. Réessaie dans une minute.',
    'boundary.title': 'Ça s’est bloqué',
    'boundary.hint':
      'La partie enregistrée sur cet appareil est illisible. Repartir de zéro règle le problème.',
    'boundary.action': 'Repartir de zéro',
    'lang.label': 'Langue',
  },

  de: {
    'app.name': 'Munchkin Räume',
    'app.tagline':
      'Level- und Ausrüstungszähler für Munchkin. Jeder führt seinen Charakter auf dem eigenen Handy, der Tisch-Bildschirm zeigt alles.',
    'setup.empty': 'Noch niemand im Spiel.',
    'setup.add': 'Spieler hinzufügen',
    'setup.start': 'Los geht’s',
    'setup.player': 'Spieler {n}',
    'setup.remove': '{name} entfernen',
    'setup.color': 'Farbe für {name}',
    'goal.label': 'Gewonnen bei Level',
    'goal.down': 'Ziellevel senken',
    'goal.up': 'Ziellevel erhöhen',
    'goal.locked': 'Wird vor dem Start festgelegt',
    'sex.male': 'Mann',
    'sex.female': 'Frau',
    'stat.level': 'Level',
    'stat.gear': 'Ausrüstung',
    'stat.bad': 'Malus',
    'stat.badLong': 'Malus (Abzug)',
    'stat.type': '{label} eingeben',
    'stat.sex': 'Geschlecht',
    'stat.force': 'Stärke',
    'stat.down': '{label} senken',
    'stat.up': '{label} erhöhen',
    'stat.lv': 'Lv',
    'sheet.back': 'Zurück zum Spielfeld',
    'player.map': 'Spielfeld ansehen',
    'player.mine': 'Mein Blatt',
    'player.switch': 'Spieler wechseln',
    'board.menu': 'Spieloptionen',
    'board.who': 'Was ist dieses Gerät?',
    'board.edit': 'Spieler bearbeiten',
    'board.restart': 'Spiel zurücksetzen',
    'board.sure': 'Sicher?',
    'board.keep': 'Weiterspielen',
    'board.restartOk': 'Zurücksetzen',
    'role.who': 'Wer bist du?',
    'role.table': 'Tisch',
    'role.tableHint': 'Der Bildschirm in der Mitte, nur zum Anschauen, spielt nicht mit.',
    'role.orPick': 'oder nimm deinen Charakter',
    'role.taken': 'hat schon jemand',
    'role.orNew': 'oder wenn heute neu angefangen wird',
    'role.newGame': 'Ganz neu anfangen',
    'role.newGameHint': 'Alles wird gelöscht, du fängst mit leerer Liste an.',
    'room.title': 'Raum',
    'room.scan': 'Zum Beitreten scannen',
    'room.orCode': 'Oder per Hand mit diesem Code:',
    'room.device': '{n} Gerät',
    'room.devices': '{n} Geräte',
    'room.privacy':
      'Die Namen gehen an einen Server bei Cloudflare, und der Raum löscht sich nach 24 h selbst.',
    'room.leave': 'Raum verlassen',
    'room.done': 'Fertig',
    'room.createHint': 'Erstelle den Raum am Tisch-Bildschirm, alle anderen kommen per Handy dazu.',
    'room.create': 'Raum erstellen',
    'room.orJoin': 'oder tritt einem bestehenden bei',
    'room.code': 'Code',
    'room.enter': 'Beitreten',
    'room.notReady':
      'Für mehrere Geräte muss der Raum-Server laufen. Bis dahin funktioniert die App vollständig auf diesem Gerät.',
    'status.idle': 'Kein Raum',
    'status.connecting': 'Verbinde…',
    'status.online': 'Verbunden',
    'status.offline': 'Keine Verbindung',
    'error.missing': 'Diesen Raum gibt es nicht mehr.',
    'error.create': 'Raum konnte nicht erstellt werden. Ist Internet da?',
    'error.code': 'Der Code hat vier Zeichen.',
    'error.tooMany': 'Zu viele Räume auf einmal. Versuch es in einer Minute.',
    'boundary.title': 'Da hat sich was verklemmt',
    'boundary.hint':
      'Das auf diesem Gerät gespeicherte Spiel ist nicht lesbar. Neu anfangen behebt es.',
    'boundary.action': 'Neu anfangen',
    'lang.label': 'Sprache',
  },

  it: {
    'app.name': 'Munchkin Stanze',
    'app.tagline':
      'Contatore di livelli ed equipaggiamento per Munchkin. Ognuno gestisce il suo personaggio dal telefono e lo schermo al centro mostra tutto.',
    'setup.empty': 'Ancora nessuno in partita.',
    'setup.add': 'Aggiungi giocatore',
    'setup.start': 'Iniziamo',
    'setup.player': 'Giocatore {n}',
    'setup.remove': 'Togli {name}',
    'setup.color': 'Colore di {name}',
    'goal.label': 'Si vince al livello',
    'goal.down': 'Abbassa il livello obiettivo',
    'goal.up': 'Alza il livello obiettivo',
    'goal.locked': 'Si decide prima di iniziare',
    'sex.male': 'Uomo',
    'sex.female': 'Donna',
    'stat.level': 'Livello',
    'stat.gear': 'Equipaggiamento',
    'stat.bad': 'Malus',
    'stat.badLong': 'Malus (sottrae)',
    'stat.type': 'Scrivi {label}',
    'stat.sex': 'Sesso',
    'stat.force': 'Forza',
    'stat.down': 'Abbassa {label}',
    'stat.up': 'Alza {label}',
    'stat.lv': 'Lv',
    'sheet.back': 'Torna al tavolo',
    'player.map': 'Vedi il tavolo',
    'player.mine': 'La mia scheda',
    'player.switch': 'Cambia giocatore',
    'board.menu': 'Opzioni della partita',
    'board.who': 'Questo apparecchio cos’è?',
    'board.edit': 'Modifica giocatori',
    'board.restart': 'Azzera la partita',
    'board.sure': 'Sei sicuro?',
    'board.keep': 'Continua a giocare',
    'board.restartOk': 'Azzera',
    'role.who': 'Tu chi sei?',
    'role.table': 'Tavolo',
    'role.tableHint': 'Lo schermo al centro, solo per guardare, non gioca.',
    'role.orPick': 'oppure prendi il tuo personaggio',
    'role.taken': 'ce l’ha già un altro',
    'role.orNew': 'oppure se oggi si riparte',
    'role.newGame': 'Ricominciare da zero',
    'role.newGameHint': 'Si cancella tutto e riparti con la lista vuota.',
    'room.title': 'Stanza',
    'room.scan': 'Inquadra per entrare',
    'room.orCode': 'Oppure entra a mano con questo codice:',
    'room.device': '{n} apparecchio',
    'room.devices': '{n} apparecchi',
    'room.privacy':
      'I nomi vanno su un server di Cloudflare e la stanza si cancella da sola dopo 24 h.',
    'room.leave': 'Esci dalla stanza',
    'room.done': 'Fatto',
    'room.createHint': 'Crea la stanza dallo schermo del tavolo e che ognuno entri dal telefono.',
    'room.create': 'Crea stanza',
    'room.orJoin': 'oppure entra in una che c’è già',
    'room.code': 'Codice',
    'room.enter': 'Entra',
    'room.notReady':
      'Per giocare con più apparecchi serve il server delle stanze. Intanto l’app funziona tutta qui.',
    'status.idle': 'Nessuna stanza',
    'status.connecting': 'Connessione…',
    'status.online': 'Connesso',
    'status.offline': 'Senza connessione',
    'error.missing': 'Quella stanza non esiste più.',
    'error.create': 'Non si è potuta creare la stanza. C’è internet?',
    'error.code': 'Il codice è di quattro lettere.',
    'error.tooMany': 'Troppe stanze di fila. Riprova tra un minuto.',
    'boundary.title': 'Si è incastrata',
    'boundary.hint':
      'La partita salvata su questo apparecchio non si legge. Ricominciando si sistema.',
    'boundary.action': 'Ricominciare',
    'lang.label': 'Lingua',
  },

  pt: {
    'app.name': 'Munchkin Salas',
    'app.tagline':
      'Contador de níveis e equipamento para Munchkin. Cada um cuida do seu personagem pelo celular e a tela da mesa mostra tudo.',
    'setup.empty': 'Ainda não tem ninguém na partida.',
    'setup.add': 'Adicionar jogador',
    'setup.start': 'Começar',
    'setup.player': 'Jogador {n}',
    'setup.remove': 'Tirar {name}',
    'setup.color': 'Cor de {name}',
    'goal.label': 'Ganha no nível',
    'goal.down': 'Baixar o nível objetivo',
    'goal.up': 'Subir o nível objetivo',
    'goal.locked': 'Decide-se antes de começar',
    'sex.male': 'Homem',
    'sex.female': 'Mulher',
    'stat.level': 'Nível',
    'stat.gear': 'Equipamento',
    'stat.bad': 'Penalidades',
    'stat.badLong': 'Penalidades (subtrai)',
    'stat.type': 'Digitar {label}',
    'stat.sex': 'Sexo',
    'stat.force': 'Força',
    'stat.down': 'Baixar {label}',
    'stat.up': 'Subir {label}',
    'stat.lv': 'Nv',
    'sheet.back': 'Voltar ao tabuleiro',
    'player.map': 'Ver o tabuleiro',
    'player.mine': 'Minha ficha',
    'player.switch': 'Trocar de jogador',
    'board.menu': 'Opções da partida',
    'board.who': 'O que é este aparelho?',
    'board.edit': 'Editar jogadores',
    'board.restart': 'Reiniciar partida',
    'board.sure': 'Tem certeza?',
    'board.keep': 'Continuar jogando',
    'board.restartOk': 'Zerar',
    'role.who': 'Quem é você?',
    'role.table': 'Mesa',
    'role.tableHint': 'A tela do meio, só para olhar, não joga.',
    'role.orPick': 'ou pegue seu personagem',
    'role.taken': 'outro já pegou',
    'role.orNew': 'ou se hoje é outra',
    'role.newGame': 'Começar do zero',
    'role.newGameHint': 'Apaga tudo e você começa com a lista vazia.',
    'room.title': 'Sala',
    'room.scan': 'Aponte para entrar',
    'room.orCode': 'Ou entre na mão com este código:',
    'room.device': '{n} aparelho',
    'room.devices': '{n} aparelhos',
    'room.privacy':
      'Os nomes vão para um servidor na Cloudflare e a sala se apaga sozinha em 24 h.',
    'room.leave': 'Sair da sala',
    'room.done': 'Pronto',
    'room.createHint': 'Crie a sala na tela da mesa e cada um entra pelo celular.',
    'room.create': 'Criar sala',
    'room.orJoin': 'ou entre numa que já existe',
    'room.code': 'Código',
    'room.enter': 'Entrar',
    'room.notReady':
      'Para jogar com vários aparelhos precisa do servidor de salas. Até então o app funciona todo aqui.',
    'status.idle': 'Sem sala',
    'status.connecting': 'Conectando…',
    'status.online': 'Conectado',
    'status.offline': 'Sem conexão',
    'error.missing': 'Essa sala não existe mais.',
    'error.create': 'Não deu para criar a sala. Tem internet?',
    'error.code': 'O código tem quatro letras.',
    'error.tooMany': 'Muitas salas seguidas. Tente em um minuto.',
    'boundary.title': 'Travou',
    'boundary.hint':
      'A partida salva neste aparelho não pode ser lida. Começando de novo resolve.',
    'boundary.action': 'Começar de novo',
    'lang.label': 'Idioma',
  },
}

const CODES = LANGS.map((l) => l.code)

// El idioma del navegador si lo tenemos; si no, ingles.
export function detect(preferred = []) {
  for (const raw of preferred) {
    const code = String(raw).slice(0, 2).toLowerCase()
    if (CODES.includes(code)) return code
  }
  return 'en'
}

export function translate(lang, key, vars) {
  const table = DICT[lang] ?? DICT.en
  const text = table[key] ?? DICT.en[key] ?? key
  if (!vars) return text
  return text.replace(/\{(\w+)\}/g, (whole, name) => (name in vars ? String(vars[name]) : whole))
}

// Se exporta porque `Boundary` es una clase y no puede usar hooks.
